runtime: nodejs
env: flex

env_variables:
  # --REQUIRED--
  DATABASE_URI: mongodb://localhost:27017/dev
  APP_ID: parse_app_id_starter
  MASTER_KEY: 1234567890
  SERVER_URL: https://localhost:1337/parse
  # --OPTIONAL--
  # FILE_KEY: <your-file-key>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  
