apiVersion: v1
kind: Service
metadata:
  name: parser-server-service
spec:
  ports:
  - port: 80
    targetPort: 1337 
    protocol: TCP
    name: parser-server-service
  type: LoadBalancer 
  selector:
    app: parser-server
